//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTTKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int IDHoaDon { get; set; }
        public int IDHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SLTra { get; set; }
        public Nullable<int> NguoiXacNhanTra { get; set; }
        public Nullable<System.DateTime> NgayXacNhanTra { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
