//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTTKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonTraHangNCC
    {
        public int IDDonTra { get; set; }
        public int IDHangHoa { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DonTraHangCC DonTraHangCC { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
