//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTTKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonNhapHang()
        {
            this.ChiTietDonNhapHangs = new HashSet<ChiTietDonNhapHang>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string LyDo { get; set; }
        public int NguoiLap { get; set; }
        public Nullable<int> NguoiXacNhan { get; set; }
        public Nullable<System.DateTime> NgayXacNhan { get; set; }
        public Nullable<int> NCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonNhapHang> ChiTietDonNhapHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
