//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTTKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int ID { get; set; }
        public int NguoiLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string ViTriDang { get; set; }
        public int IDDoiTac { get; set; }
    
        public virtual DoiTacQuangCao DoiTacQuangCao { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
