//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTTKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int IDHangHoa { get; set; }
        public int IDKhachHang { get; set; }
        public System.DateTime Ngay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NguoiGui { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
